-- ============================================================
-- 004_seed_posts_remaining: blog posts seed (continuation)
--
-- 실 데이터 시드는 scripts/seed/posts.sql (gitignored, 003 와 합본) 으로 이전.
-- 신규 환경 구축 시 별도 적용 필요. 자세한 가이드는 scripts/seed/README.example.md 참고.
-- ============================================================
